### PR TITLE
Add skin for broot

### PR DESCRIPTION
**Pull request by barskern**

### CODE REVIEW

**Comment by MindTooth** [comment]
Holding off merging awaiting https://github.com/srcery-colors/srcery-vim/pull/45.

**Comment by MindTooth** [comment]
The color swap is now merged upstream.  If you could take a look if any changes affect this, I'll merge when ready. 😄

**Comment by barskern** [comment]
Sorry for the lack of response, I will take a look. :smile:

**Comment by barskern** [comment]
@MindTooth I did use `white` in a few places, hence it has been updated to the new color now. This should be squashed prior to merge.

**Comment by MindTooth** [comment]
Thank you for your contribution to the project. 😊

**Pull request merged**
